"""Gurobi C language code generator.

Generates C source code from IR JSON using the GRB C API (178 functions).
Based on the complete Gurobi C API documentation analysis.

Key C-specific concerns:
- Manual memory management (malloc/free for arrays)
- Double pointer indirection for attributes (double *val, int *ival)
- Lazy update semantics (GRBupdatemodel before querying)
- Callback function pointers
- C99/C11 standard compliance
"""

from __future__ import annotations

from orpilot.codegen.backends import SolverBackend, registry


@registry.register("gurobi-c")
class GurobiCBackend(SolverBackend):
    """Generates C source code using the Gurobi C API (GRB*.h).

    Produces a standalone C file with:
    - #include "gurobi_c.h"
    - int solve(int argc, char *argv[]) entry point
    - GRBenv/GRBmodel lifecycle management
    - Full error checking with GRBgeterrormsg
    """

    @property
    def solver_name(self) -> str:
        return "gurobi-c"

    @property
    def display_name(self) -> str:
        return "Gurobi C (GRB C API)"

    def compile(self, ir: dict) -> str:
        sets = ir.get("sets", {})
        variables = ir.get("variables", {})
        constraints = ir.get("constraints", {})
        sense = ir.get("sense", "minimize")
        problem_class = ir.get("problem_class", "Model")

        lines: list[str] = []
        self._emit_header(lines)
        self._emit_main_start(lines, problem_class)

        # Set loading (simplified — C version reads from CSV via custom parser)
        self._emit_c_set_loading(lines, sets)

        # Variable creation
        self._emit_c_variables(lines, variables, sets)

        # Constraints
        self._emit_c_constraints(lines, constraints, variables, sets)

        # Objective
        self._emit_c_objective(lines, ir.get("objective", {}), sense, variables)

        # Solve and output
        self._emit_c_solve(lines)
        self._emit_c_cleanup(lines)

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------

    def _emit_header(self, lines: list[str]) -> None:
        lines.extend([
            '/* Auto-generated by OR-Copilot Gurobi C backend */',
            '#include <stdlib.h>',
            '#include <stdio.h>',
            '#include <string.h>',
            '#include "gurobi_c.h"',
            '',
            '#define CHECK_ERROR(err, env, msg) \\',
            '    if (err) { \\',
            '        fprintf(stderr, "Error %d: %s\\n", err, GRBgeterrormsg(env)); \\',
            '        goto QUIT; \\',
            '    }',
            '',
        ])

    def _emit_main_start(self, lines: list[str], name: str) -> None:
        lines.extend([
            f'int solve_{name}(int argc, char *argv[]) {{',
            '    GRBenv   *env   = NULL;',
            '    GRBmodel *model = NULL;',
            '    int       error = 0;',
            '',
            '    /* Create environment */',
            '    error = GRBemptyenv(&env);',
            '    CHECK_ERROR(error, env, "GRBemptyenv");',
            '    error = GRBstartenv(env);',
            '    CHECK_ERROR(error, env, "GRBstartenv");',
            '',
        ])

    # ------------------------------------------------------------------
    # Set loading (simplified C version)
    # ------------------------------------------------------------------

    def _emit_c_set_loading(self, lines: list[str], sets: dict) -> None:
        lines.append('    /* --- Set dimensions --- */')
        for set_name, meta in sets.items():
            size = meta.get("size", 0)
            if size:
                lines.append(f'    int    N_{set_name}  = {size};  /* {set_name} */')
            else:
                lines.append(f'    int    N_{set_name}  = 0;  /* TODO: load from file */')
        lines.append('')

    # ------------------------------------------------------------------
    # Variables
    # ------------------------------------------------------------------

    def _emit_c_variables(self, lines: list[str], variables: dict, sets: dict) -> None:
        lines.append('    /* --- Create empty model --- */')
        lines.append('    error = GRBnewmodel(env, &model, "model", 0, NULL, NULL, NULL, NULL, NULL);')
        lines.append('    CHECK_ERROR(error, env, "GRBnewmodel");')
        lines.append('')

        vtype_map = {
            "continuous": "GRB_CONTINUOUS",
            "integer": "GRB_INTEGER",
            "binary": "GRB_BINARY",
        }

        for var_name, meta in variables.items():
            domain = meta.get("domain", [])
            vtype = vtype_map.get(meta.get("type", "continuous"), "GRB_CONTINUOUS")
            lb = meta.get("lower_bound", 0.0)
            ub = meta.get("upper_bound")
            ub_str = str(float(ub)) if ub is not None else "GRB_INFINITY"

            if not domain:
                lines.append(
                    f'    /* {var_name}: {meta.get("description", "")} */'
                )
                lines.append(f'    int idx_{var_name};')
                lines.append(
                    f'    error = GRBaddvar(model, 0, NULL, NULL, {lb}, {ub}, '
                    f'0.0, {vtype}, "{var_name}");'
                )
                lines.append(f'    CHECK_ERROR(error, env, "GRBaddvar/{var_name}");')
                lines.append(
                    f'    GRBgetintattr(model, GRB_INT_ATTR_NUMVARS, &idx_{var_name});'
                )
                lines.append(f'    idx_{var_name} -= 1;  /* zero-based index */')
            else:
                lines.append(f'    /* {var_name}: indexed over {domain} */')
                for d in domain:
                    lines.append(f'    /* Iterating over {d}... */')
                lines.append(
                    f'    /* TODO: Loop variable creation for indexed variables */'
                )
            lines.append('')

    # ------------------------------------------------------------------
    # Constraints
    # ------------------------------------------------------------------

    def _emit_c_constraints(self, lines: list[str], constraints: dict,
                            variables: dict, sets: dict) -> None:
        lines.append('    /* --- Constraints --- */')
        sense_map = {"=": "GRB_EQUAL", "<=": "GRB_LESS_EQUAL", ">=": "GRB_GREATER_EQUAL"}

        for cname, cmeta in constraints.items():
            sense = sense_map.get(cmeta.get("sense", "<="), "GRB_LESS_EQUAL")
            lines.append(
                f'    /* {cname}: {cmeta.get("description", "")} */'
            )
            lines.append(
                f'    /* TODO: Add constraint {cname} with sense {sense} */'
            )
            lines.append('')

    # ------------------------------------------------------------------
    # Objective
    # ------------------------------------------------------------------

    def _emit_c_objective(self, lines: list[str], objective: dict,
                          sense: str, variables: dict) -> None:
        lines.append('    /* --- Objective --- */')
        obj_sense = "GRB_MINIMIZE" if sense == "minimize" else "GRB_MAXIMIZE"
        lines.append(f'    error = GRBsetintattr(model, GRB_INT_ATTR_MODELSENSE, {obj_sense});')
        lines.append('    CHECK_ERROR(error, env, "set modelsense");')
        lines.append('')

    # ------------------------------------------------------------------
    # Solve
    # ------------------------------------------------------------------

    def _emit_c_solve(self, lines: list[str]) -> None:
        lines.extend([
            '    /* --- Solve --- */',
            '    error = GRBoptimize(model);',
            '    CHECK_ERROR(error, env, "GRBoptimize");',
            '',
            '    /* --- Extract results --- */',
            '    int status;',
            '    error = GRBgetintattr(model, GRB_INT_ATTR_STATUS, &status);',
            '    CHECK_ERROR(error, env, "get status");',
            '',
            '    if (status == GRB_OPTIMAL) {',
            '        double objval;',
            '        error = GRBgetdblattr(model, GRB_DBL_ATTR_OBJVAL, &objval);',
            '        CHECK_ERROR(error, env, "get objval");',
            '        printf("Optimal objective: %f\\n", objval);',
            '',
            '        /* Extract variable values */',
            '        int numvars;',
            '        GRBgetintattr(model, GRB_INT_ATTR_NUMVARS, &numvars);',
            '        double *x = (double *)malloc(numvars * sizeof(double));',
            '        if (x) {',
            '            error = GRBgetdblattrarray(model, GRB_DBL_ATTR_X, 0, numvars, x);',
            '            CHECK_ERROR(error, env, "get X");',
            '            for (int i = 0; i  numvars; i++) {',
            '                printf("  var[%d] = %f\\n", i, x[i]);',
            '            }',
            '            free(x);',
            '        }',
            '    } else if (status == GRB_INFEASIBLE) {',
            '        printf("Model is infeasible.\\n");',
            '    } else if (status == GRB_UNBOUNDED) {',
            '        printf("Model is unbounded.\\n");',
            '    }',
            '',
        ])

    def _emit_c_cleanup(self, lines: list[str]) -> None:
        lines.extend([
            'QUIT:',
            '    if (model) GRBfreemodel(model);',
            '    if (env)   GRBfreeenv(env);',
            '    return error;',
            '}',
        ])
